spring:
  config:
    import: optional:configserver:http://localhost:8888 # profile phase 마다 config repo를 별도로 둘 것인가?
  cloud:
    config:
      name: fund,account,bank,common
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: busrefresh
