spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      name: fund,account,bank,common

management:
  endpoints:
    web:
      exposure:
        include: refresh

